#!/usr/bin/env bash
rm -f ./my ./egger
find test/semenal -maxdepth 1 -name "*.mod" -print0 | xargs -0 -L1 -I{} -- sh -c "snuplc/test_parser {} >> my"
find test/semanal -maxdepth 1 -name "*.mod" -print0 | xargs -0 -L1 -I{} -- sh -c "reference/3_test_parser {} >> egger"

